# Generated by Django 4.2.23 on 2025-08-03 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_plantprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantprofile',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='plantprofile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='plantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plantprofile',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/'),
        ),
    ]
