# Generated by Django 4.2.23 on 2025-08-04 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_plantprofile_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCareReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pruning', 'Pruning'), ('repotting', 'Repotting'), ('sunlight', 'Sunlight')], max_length=20)),
                ('reminder_date', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.plantprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
